apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: libvirtmachineproviderconfigs.libvirtproviderconfig.k8s.io
spec:
  group: libvirtproviderconfig.k8s.io
  names:
    kind: LibvirtMachineProviderConfig
    plural: libvirtmachineproviderconfigs
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        domainMemory:
          format: int64
          type: integer
        domainVCPU:  
          format: int
          type: integer
        networkUUID:
          type: string
        networkInterfaceName:
          type: string
        networkInterafceAddress:
          type: string
        networkInterfaceHostname:
          type: string
        autoStart:
          type: boolean  
        URI:
          type: string
        ignKey:
          type: string    
        status:
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
