apiVersion: v1
kind: Secret
metadata:
  name: libvirt-actuator-user-data-secret
  namespace: test
type: Opaque
data:
  userData: |
    IyEvYmluL2Jhc2gKCmNhdCA8PEhFUkVET0MgPiAvcm9vdC91c2VyLWRhdGEuc2gKIyEvYmluL2Jh
    c2gKY2F0IDw8RU9GID4gL2V0Yy95dW0ucmVwb3MuZC9rdWJlcm5ldGVzLnJlcG8KW2t1YmVybmV0
    ZXNdCm5hbWU9S3ViZXJuZXRlcwpiYXNldXJsPWh0dHBzOi8vcGFja2FnZXMuY2xvdWQuZ29vZ2xl
    LmNvbS95dW0vcmVwb3Mva3ViZXJuZXRlcy1lbDcteDg2XzY0CmVuYWJsZWQ9MQpncGdjaGVjaz0x
    CnJlcG9fZ3BnY2hlY2s9MQpncGdrZXk9aHR0cHM6Ly9wYWNrYWdlcy5jbG91ZC5nb29nbGUuY29t
    L3l1bS9kb2MveXVtLWtleS5ncGcgaHR0cHM6Ly9wYWNrYWdlcy5jbG91ZC5nb29nbGUuY29tL3l1
    bS9kb2MvcnBtLXBhY2thZ2Uta2V5LmdwZwpleGNsdWRlPWt1YmUqCkVPRgpzZXRlbmZvcmNlIDAK
    eXVtIGluc3RhbGwgZG9ja2VyIC15CnN5c3RlbWN0bCBlbmFibGUgZG9ja2VyCnN5c3RlbWN0bCBz
    dGFydCBkb2NrZXIKeXVtIGluc3RhbGwgLXkga3ViZWxldC0xLjExLjMga3ViZWFkbS0xLjExLjMg
    a3ViZWN0bC0xLjExLjMgLS1kaXNhYmxlZXhjbHVkZXM9a3ViZXJuZXRlcwpjYXQgPDxFT0YgPiAv
    ZXRjL2RlZmF1bHQva3ViZWxldApLVUJFTEVUX0tVQkVBRE1fRVhUUkFfQVJHUz0tLWNncm91cC1k
    cml2ZXI9c3lzdGVtZApFT0YKZWNobyAnMScgPiAvcHJvYy9zeXMvbmV0L2JyaWRnZS9icmlkZ2Ut
    bmYtY2FsbC1pcHRhYmxlcwprdWJlYWRtIGluaXQgLS1hcGlzZXJ2ZXItYmluZC1wb3J0IDg0NDMg
    LS10b2tlbiAyaXF6cW0uODViczB4Nm1peXgxbm03bCAtLWFwaXNlcnZlci1jZXJ0LWV4dHJhLXNh
    bnM9MTI3LjAuMC4xIC0tcG9kLW5ldHdvcmstY2lkcj0xOTIuMTY4LjAuMC8xNiAtdiA2CiMgRW5h
    YmxlIG5ldHdvcmtpbmcgYnkgZGVmYXVsdC4Ka3ViZWN0bCBhcHBseSAtZiBodHRwczovL3Jhdy5n
    aXRodWJ1c2VyY29udGVudC5jb20vY2xvdWRuYXRpdmVsYWJzL2t1YmUtcm91dGVyL21hc3Rlci9k
    YWVtb25zZXQva3ViZWFkbS1rdWJlcm91dGVyLnlhbWwgLS1rdWJlY29uZmlnIC9ldGMva3ViZXJu
    ZXRlcy9hZG1pbi5jb25mCm1rZGlyIC1wIC9yb290Ly5rdWJlCmNwIC1pIC9ldGMva3ViZXJuZXRl
    cy9hZG1pbi5jb25mIC9yb290Ly5rdWJlL2NvbmZpZwpjaG93biAkKGlkIC11KTokKGlkIC1nKSAv
    cm9vdC8ua3ViZS9jb25maWcKSEVSRURPQwoKYmFzaCAvcm9vdC91c2VyLWRhdGEuc2ggPiAvcm9v
    dC91c2VyLWRhdGEubG9ncwo=
